# Deployed code version: __CODE_VERSION__
version: '2'
services:
  web:
    restart: unless-stopped
    image: bluesky-web
    container_name: bluesky-web
    ports:
    - 8888:8888
    volumes:
    - ./docker-logs/web/:/var/log/blueskyweb/
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - mongo
    # note: log should be in /var/log/blueskyweb/bluesky-web.log, the default
    command: bsp-web -b bluesky --path-prefix=bluesky --mongodb-url=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb -p 8888 --log-level=DEBUG
  mongo:
    restart: unless-stopped
    image: mongo
    container_name: bluesky-web-mongo
    environment:
    # These are meant to be overridden
    - MONGO_INITDB_ROOT_USERNAME=blueskyweb
    - MONGO_INITDB_ROOT_PASSWORD=blueskywebmongopassword
    ports:
    - 27018:27017
    volumes:
    - ./docker-logs/mongodb/:/var/log/mongodb/
    - ./docker-data/db/configdb/:/data/db/
    - ./docker-data/mongodb/configdb/:/data/configdb/
  worker_all_met:
    restart: unless-stopped
    image: bluesky-web
    container_name: bluesky-web-worker-all-met
    volumes:
    - ./docker-logs/worker/all-met/:/var/log/blueskyworker/
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MONGODB_URL://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    command: celery -Q all-met -c 5 -A blueskyworker.tasks worker -l DEBUG -f /var/log/blueskyworker/bluesky-web-worker-all-met.log
  worker_dri:
    restart: unless-stopped
    image: bluesky-web
    container_name: bluesky-web-worker-dri
    volumes:
    - ./docker-logs/worker/dri/:/var/log/blueskyworker/
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MONGODB_URL://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    command: celery -Q dri -c 5 -A blueskyworker.tasks worker -l DEBUG -f /var/log/blueskyworker/bluesky-web-worker-dri.log
  worker_nam:
    restart: unless-stopped
    image: bluesky-web
    container_name: bluesky-web-worker-nam
    volumes:
    - ./docker-logs/worker/nam/:/var/log/blueskyworker/
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MONGODB_URL://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    command: celery -Q nam -c 5 -A blueskyworker.tasks worker -l DEBUG -f /var/log/blueskyworker/bluesky-web-worker-nam.log
