# Deployed code version: __CODE_VERSION__
version: '2'
services:
  web:
    restart: unless-stopped
    container_name: bluesky-web
    image: bluesky-web
    ports:
    - 8888:8888
    volumes:
    - ./docker-logs/web/:/var/log/blueskyweb/
    links:
    - mongo
    # note: log should be in /var/log/blueskyweb/blueskyweb.log, the default
    command: blueskyweb --mongodb-url=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb -p 8888 --log-level=DEBUG
  mongo:
    restart: unless-stopped
    container_name: bluesky-mongo
    image: mongo
    environment:
    # These are meant to be overridden
    - MONGO_INITDB_ROOT_USERNAME=blueskyweb
    - MONGO_INITDB_ROOT_PASSWORD=blueskywebmongopassword
    ports:
    - 27018:27017
    volumes:
    - ./docker-logs/mongodb/:/var/log/mongodb/
    - ./docker-data/mongodb/configdb/:/data/configdb/
  # rabbitmq:
  #   restart: unless-stopped
  #   container_name: bluesky-web-rabbitmq
  #   image: rabbitmq:alpine