# *** This docker-compose.yml is for dev purposes ***
# Note: letting restart policy be the default 'no' so that
#   I don't have to explicity call 'down' to free up web and mongo
#   ports in case I want to switch to running processes manually
#   or with foreman
version: '2'
services:
  mongo:
    image: mongo:3.4.6
    container_name: bluesky-web-mongo
    environment:
    # These are meant to be overridden
    - MONGO_INITDB_ROOT_USERNAME=blueskywebadmin
    - MONGO_INITDB_ROOT_PASSWORD=blueskywebmongopasswordadmin
    ports:
    - 27018:27017
    volumes:
    - $PWD/docker-logs/mongodb/:/var/log/mongodb/
    - $PWD/docker-data/mongodb/db/:/data/db/
    - $PWD/docker-data/mongodb/configdb/:/data/configdb/
    - $PWD/dev/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    # Note: '--auth' is automatically added to command if
    #   MONGO_INITDB_ROOT_[USERNAME|PASSWORD] are set, but we need to
    #   set `command` in order to specify `--logpath`
    command: mongod --auth --logpath /var/log/mongodb/mongodb.log
  web1:
    image: bluesky-web
    container_name: bluesky-web-1
    volumes:
    - $PWD/:/usr/src/blueskyweb/
    - $PWD/docker-logs/web/:/var/log/blueskyweb/
    - $PWD/dev/config.json:/etc/bluesky-web/config.json
    - /var/run/docker.sock:/var/run/docker.sock
    # Note: output root dir has to be the same on host and in container,
    #   since bsp container will have the same mount
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    links:
    - mongo
    # note: log should be in /var/log/blueskyweb/bluesky-web.log, the default
    command: bsp-web -d -o $PWD/docker-data/output
      --path-prefix=bluesky-web -p 80
      --mongodb-url=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb
      --log-level=DEBUG
      --log-file=/var/log/blueskyweb/bluesky-web.log
      --output-url-scheme=http --output-url-port=8886
      --output-url-path-prefix= --bluesky-log-level=DEBUG
      -c /etc/bluesky-web/config.json
  web2:
    image: bluesky-web
    container_name: bluesky-web-2
    volumes:
    - $PWD/:/usr/src/blueskyweb/
    - $PWD/docker-logs/web/:/var/log/blueskyweb/
    - $PWD/dev/config.json:/etc/bluesky-web/config.json
    - /var/run/docker.sock:/var/run/docker.sock
    # Note: output root dir has to be the same on host and in container,
    #   since bsp container will have the same mount
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    links:
    - mongo
    # note: log should be in /var/log/blueskyweb/bluesky-web.log, the default
    command: bsp-web -d -o $PWD/docker-data/output
      --path-prefix=bluesky-web -p 80
      --mongodb-url=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb
      --log-level=DEBUG
      --log-file=/var/log/blueskyweb/bluesky-web.log
      --output-url-scheme=http --output-url-port=8886
      --output-url-path-prefix= --bluesky-log-level=DEBUG
      -c /etc/bluesky-web/config.json
  nginx:
    restart: unless-stopped
    container_name: bluesky-web-nginx
    image: bluesky-web-nginx
    ports:
    - 8887:80
    volumes:
    - ./docker-logs/nginx/:/var/log/nginx/
    links:
    - web1
    - web2
  output_web:
    image: python:3.5-alpine
    container_name: bluesky-web-output
    ports:
    - 8886:8886
    volumes:
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    working_dir: $PWD/docker-data/output/
    command: python -m http.server 8886
  worker_no_met:
    image: bluesky-web
    container_name: bluesky-web-worker-no-met
    volumes:
    - $PWD/:/usr/src/blueskyweb/
    - $PWD/docker-logs/worker/no-met/:/var/log/blueskyworker/
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    - /var/run/docker.sock:/var/run/docker.sock
    # - $HOME/DRI_6km/:/data/Met/CANSAC/6km/ARL/
    # - $HOME/NAM84/:/data/Met/NAM/12km/ARL/
    links:
    - mongo
    environment:
    #- MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    - MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb
    - PUBLIC_HOSTNAME=localhost
    command: celery -Q no-met -c 5 -A blueskyworker.tasks worker
      -l INFO -f /var/log/blueskyworker/bluesky-web-worker-no-met.log
  worker_ca-nv_6-km:
    image: bluesky-web
    container_name: bluesky-web-worker-ca-nv_6-km
    volumes:
    - $PWD/:/usr/src/blueskyweb/
    - $PWD/docker-logs/worker/ca-nv_6-km/:/var/log/blueskyworker/
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    - /var/run/docker.sock:/var/run/docker.sock
    # mount met for ofelia
    # Note: met root dir has to be the same on host and in this container,
    #   since bsp container will have the same mount
    - $HOME/DRI_6km/:$HOME/DRI_6km/
    links:
    - mongo
    environment:
    #- MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    - MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb
    - PUBLIC_HOSTNAME=localhost
    command: celery -Q ca-nv_6-km -c 5 -A blueskyworker.tasks worker
      -l INFO -f /var/log/blueskyworker/bluesky-web-worker-ca-nv_6-km.log
  worker_national_12-km:
    image: bluesky-web
    container_name: bluesky-web-worker-national_12-km
    volumes:
    - $PWD/:/usr/src/blueskyweb/
    - $PWD/docker-logs/worker/national_12-km/:/var/log/blueskyworker/
    - $PWD/docker-data/output/:$PWD/docker-data/output/
    - /var/run/docker.sock:/var/run/docker.sock
    # mount met for ofelia
    - $HOME/NAM84/:$HOME/NAM84/
    links:
    - mongo
    environment:
    #- MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@localhost:27018/blueskyweb
    - MONGODB_URL=mongodb://blueskyweb:blueskywebmongopassword@mongo/blueskyweb
    - PUBLIC_HOSTNAME=localhost
    command: celery -Q national_12-km -c 5 -A blueskyworker.tasks worker
      -l INFO -f /var/log/blueskyworker/bluesky-web-worker-national_12-km.log
  ofelia:
    image: mcuadros/ofelia
    container_name: bluesky-web-ofelia
    volumes:
    - $PWD/dev/ofelia.ini:/etc/ofelia/config.ini
    - /var/run/docker.sock:/var/run/docker.sock
    #command: ofelia daemon --config /etc/ofelia/config.ini
